### ISSUE TITLE
Implement Cylinders

### ISSUE THREAD

**Issue by TommasoArmadillo** [andreasala98/NM4PIG#14]
Today we talked about implementing cylinders. [Here](https://www.pbr-book.org/3ed-2018/Shapes/Cylinders) there is a reference for implementing the ray  intersection method. This is the same place where we took the one for boxes!

**Comment by andreasala98** [comment]
Sounds great to me. Let's remember our [final goal](https://www.rayrender.net/reference/pig.html)!
