### ISSUE TITLE
CSG bug

### ISSUE THREAD

**Issue by andreasala98** [andreasala98/NM4PIG#16]
Hi,
I was trying to implement [this shape](https://upload.wikimedia.org/wikipedia/commons/8/8b/Csg_tree.png) and I found a bug in CSGIntersection (it could also be in CSGDifference). The error log is quite long, it says something like
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Trace.CSGIntersection.rayIntersection(Ray ray) in /Users/andreasala/Desktop/cngif/NM4PIG/Trace/CSG.cs:line 296
```
so it's probably related to the RayIntersectionList method.

We will need to spend some time on this, soon or later!

**Comment by PietroKlausner** [comment]
@andreasala98, could you show us the build that you used for that complicated shape? Also, did you have problems when you made a CSG shape out of CSG Shapes, or was it already bugged when you tried a CSG with "primitive" Shapes?

**Comment by andreasala98** [comment]
Hey @PietroKlausner, below is the code I used to (try to) generate that shape. As you can see from [this](https://github.com/andreasala98/NM4PIG/blob/cylinder/Examples/Demo/TripleCylinder.png) the cylinder part works fine, because it is made of CSG Unions only. On the other hand, the CSG intersection between the Cube and the Sphere fails when the sphere exceeds the faces of the cube. It works fine when the sphere is fully inside the cube (i.e. the result of the intersection is just the blue sphere)

```
                    Shape C1 = new Cylinder(Tsf.Scaling(0.5f, 0.5f, 1.5f), cylMat);
                    Shape C2 = new Cylinder(Tsf.RotationY(Utility.DegToRad(45)) * 
                                            Tsf.RotationX(CC.PI / 2f) * 
                                            Tsf.Scaling(0.5f, 0.5f, 1.5f), cylMat);
                    Shape C3 = new Cylinder(Tsf.RotationX(Utility.DegToRad(-45)) * 
                                            Tsf.RotationY(CC.PI / 2f) * 
                                            Tsf.Scaling(0.5f, 0.5f, 1.5f), cylMat);

                    Shape S1 = new Sphere(Tsf.Scaling(1.5f), BrightBlueMat);
                    Shape B1 = new Box(material: BrightRedMat);

                    Shape left = S1 * B1; // intersection
                    Shape right = (C1 + C2) + C3; //union

                    Shape tot = left - right; //difference

                    world.addShape(tot);
```

**Comment by PietroKlausner** [comment]
This bug should be' fixed now.  Can I close the issue?

**Comment by andreasala98** [comment]
Ok for me!
